/*
 * This source file was generated by the Gradle 'init' task
 */
package com.zapdy.asciimediarenderer;

public class Main {
    public String getGreeting() {
        return "Ascii Media Renderer";
    }

    public static void main(String[] args) {
        System.out.println(new Main().getGreeting());
    }
}
