/*
 * This source file was generated by the Gradle 'init' task
 */
package com.zapdy.asciimediarenderer;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class MainTest {
    @Test void appHasAGreeting() {
        assertEquals(true, true); 
    }
}
